### ISSUE TITLE
Allow properties without binding

### ISSUE THREAD

**Issue by Oleksiivanov** [bpmn-io/element-templates#4]
__What should we do?__

allow properties without binding (or an explicit one for UI-only). If they are only necessary for conditional evaluation in the UI, but not for the data model of the process.

__Why should we do it?__

Sometimes we need conditional in the UI, like in this situation https://github.com/camunda/connector-sendgrid/pull/91/files/edbb7e6c85240b297e452f4d80acd74b0b29e95b#r966708812 

```js
{
  "value": "value",
  "type": "Dropdown",
  "choices": [
    {
      "value": "one"
    },
    {
      "value": "two"
    }
  ],
  "binding": { // this is not need when we use our value only for UI
    "type": "zeebe:input",
    "name": "apiKey"
  }
}

// if 'one' -> show one section, if two -> show another section
```

**Comment by pinussilvestrus** [comment]
Thanks for the feature request! 

As far as I know, that would also need a change in the [conditional checker logic](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/provider/cloud-element-templates/ElementTemplatesConditionChecker.js) since the conditions are evaluated based on XML properties (/cc @barmac @smbea). 

If no binding is specified, how would you persist the selected value from the dropdown?

**Comment by barmac** [comment]
Perhaps instead of binding-less properties, we could make use of [the recently implemented  `zeebe:Properties`](https://github.com/camunda/element-templates-json-schema/issues/65). This allows to persist the value in the XML while it does not affect the execution. In the upcoming [Camunda (Desktop) Modeler 5.3.0](https://github.com/camunda/camunda-modeler/blob/master/CHANGELOG.md#530) release, you should be able to test this in action.

**Comment by nikku** [comment]
> https://github.com/bpmn-io/element-templates/issues/4#issuecomment-1241740251

This is my gut feeling, too. I'll look into the issue tomorrow.

Generally speaking I _think_ we should not support bindingless properties. And even binding static inputs (that are not evaluated) are an option.

**Comment by nikku** [comment]
Let us not pursue this direction.

Instead, let us encourage a style where modes are clearly serialized into the XML through any of the possible mechanisms. 

As I've stated in https://github.com/camunda/connector-sendgrid/pull/91/files#r974447227 you'd need that mode anyway if you build a generic connector run-time (see also Slack connector as an example).

You can also serialize fake data (via header and/or input) that is not interpreted by the user. That is done in the Sendgrid case and a fine workaround.
